Feature/privileged checkin
informatik-mannheim/HSMA-CTT pull request #133
Opened 2021-05-18 18:29 UTC by emely3h

Wenn beim Raum-Checkin an die URL "&privileged=true" angehängt wird, dann wird die Checkin Seite um die Abschnitte "Immunitätsnachweis" und "Raum zurücksetzen" erweitert.
Durch den Button "Anzeige aktualisieren" wird die gesamte Seite neu geladen.
Durch den Button "Raum zurücksetzen" wird der User auf eine weitere Seite weitergeleitet, wo er den Raum-reset nochmal bestätigen muss, bevor alle Personen ausgecheckt werden. Nach dem Raum-reset landet der User wieder auf der Checkin Seite. Ich glaube wo der User nach dem reset landet hatten wir noch nicht besprochen, ich bin mal von der Checkin Seite ausgegangen.
(Das war mein erstes enhancement, kann gut sein, wahrscheinlich habe ich einige Dinge sehr umständlich gemacht, also gerne viel Feedback geben.)

2021-05-19 15:06 UTC, MorMundHS-MA requested changes
Nur ein paar kleine Detailänderungen, sonst funktioniert es sehr gut!

> Nach dem Raum-reset landet der User wieder auf der Checkin Seite. Ich glaube wo der User nach dem reset landet hatten wir noch nicht besprochen, ich bin mal von der Checkin Seite ausgegangen.

Jep denke das macht Sinn.

2021-05-19 15:06 UTC, MorMundHS-MA commented on src/main/java/de/hs_mannheim/informatik/ct/controller/RoomController.java
> +    @GetMapping("/{roomId}/executeRoomReset")
HTTP Requests die etwas 'tun', also den State der Anwendung verändern respektive in die DB schreiben, müssen immer `POST` (Bzw. in APIs auch `PUT`, `DELETE`...) Requests sein. Das hat zum einen Sicherheitshintergründe -> [CSRF](https://owasp.org/www-community/attacks/csrf) und zu verhindern das die Request von einem Cache bedient wird.

2021-05-19 15:06 UTC, MorMundHS-MA commented on src/main/java/de/hs_mannheim/informatik/ct/controller/RoomController.java
> +        return "redirect:/r/noId?roomId=" + roomId + "&privileged=true";
Auch hier direkter Room Link statt `r/noID`

2021-05-19 15:06 UTC, MorMundHS-MA commented on src/main/java/de/hs_mannheim/informatik/ct/controller/RoomController.java
> +            return "redirect:/r/noId?roomId=" + roomId;
Auch hier direkter Room Link statt r/noID

2021-05-19 15:06 UTC, MorMundHS-MA commented on src/main/resources/templates/rooms/checkIn.html
> +        .show{
Die Styles brauchst du glaube ich nicht mehr mit `th:if`. Und `.show` würde ich nicht verwenden da es bei Elementen die Standardmäßig ein anderes display Value haben nicht funktioniert. Z.b. `<span>` ist `display:inline`. Statt dessen kann man einfach die `.hide` class entfernen/weg lassen um etwas anzuzeigen.

2021-05-20 11:01 UTC, emely3h commented
Hi, danke für die Rückmeldung, habe alles umgesetzt bis auf einen Punkt. Dazu habe ich noch eine Rückfrage:
localhost:8080/r/A007a&privileged=true wirft immer einen 404 Fehler.
Weißt du spontan warum bzw. ich verstehe allgemein nicht, warum es den http://localhost:8080/r/noId?roomId=A007a link gibt bzw. was da der Unterschied ist zu dem link nur mit der RoomId.

2021-05-20 12:05 UTC, MorMundHS-MA commented
> Weißt du spontan warum bzw. ich verstehe allgemein nicht, warum es den http://localhost:8080/r/noId?roomId=A007a link gibt bzw. was da der Unterschied ist zu dem link nur mit der RoomId.

Die noId ist eigentlich für die Suche auf der Startseite. Aber finde den Namen auch verwirrend, es sollte denke ich `/r/search?roomId` sein und eine eigene Methode im Controller haben, aber das ist ein anderer Punkt.

>Hi, danke für die Rückmeldung, habe alles umgesetzt bis auf einen Punkt. Dazu habe ich noch eine Rückfrage:
localhost:8080/r/A007a&privileged=true wirft immer einen 404 Fehler.

Die URL ist so nicht gültig. Allgemein sind Urls so: `[host]/[page]?[param1=x]&[param2=y]&[param3....]`
D.h. `&` trennt mehrer Parameter voneinander, aber der Rest der URL wird von den Parametern mit `?` getrennt. Für alle Details empfehl ich die [MDN](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL).

Also <localhost:8080/r/A007a?privileged=true> sollte funktionieren.

2021-05-20 14:46 UTC, emely3h commented
Alles klar, danke dir. Dann sollte es jetzt passen.

2021-05-21 13:47 UTC, MorMundHS-MA approved these changes

2021-05-21 13:47 UTC, merged