Feature/frontend veranstaltungsleiterportal
informatik-mannheim/HSMA-CTT pull request #145
Opened 2021-07-01 11:24 UTC by maxones25

Ich habe das Front- und Backend für das Veranstaltungsleitenden-Portal implementiert. Man kann von der Seite die Raumauslastung sehen, welche sich autom. aktualisiert. Ist die Raumauslastung überschritten, wird sie rot eingefärbt. Des Weiteren kann man den Raum zurücksetzen. Der Veranstaltungsleitende kann sich über die Seite auschecken.

2021-07-14 22:43 UTC, MorMundHS-MA requested changes
Funktioniert gut und direkt mit Tests 👍 

Der Stil der UI ist sehr unterschiedlich zu dem normalen Check-In, aber vllt ist das ja ganz gut!

2021-07-14 22:43 UTC, MorMundHS-MA commented on src/main/java/de/hs_mannheim/informatik/ct/controller/RoomController.java
> +        val isRoomOvercrowded = room.getMaxCapacity()<=currentRoomVisitorCount;
Kannst das File nochmal neu formatieren.

2021-07-14 22:43 UTC, MorMundHS-MA commented on src/main/java/de/hs_mannheim/informatik/ct/controller/RoomController.java
> +        val roomResetEndpoint = "/r/"+roomId+"/executeRoomReset?redirectURI="+redirectURI;
Funktioniert auf jeden Fall, aber bin am überlegen ob es mit einer REST request aus JavaScript eleganter wäre als der doppel redirect. Können wir vllt im Jour Fixe entscheiden, ob sichs dafür lohnt JS voraus zusetzen.

2021-07-14 22:43 UTC, MorMundHS-MA commented on src/main/resources/templates/rooms/checkIn.html
> +            <!--<div  th:if="${privileged}">
Den Code kannst du komplett löschen, falls wir ihn nochmal brauchen kann mans ja in der git history finden.

2021-07-29 16:03 UTC, MorMundHS-MA requested changes

2021-07-29 16:03 UTC, MorMundHS-MA commented on src/main/resources/templates/rooms/veranstaltungsleitenden-portal.html
> +						fetch("rest-room-reset")
Die Room PIN sollte hier mit gesendet werden. Ist zwar keine perfekte security aber besser als nichts.

2021-08-05 10:29 UTC, maxones25 commented on src/main/java/de/hs_mannheim/informatik/ct/controller/RoomController.java
> +    @GetMapping(value = "/{roomId}/rest-room-reset", produces = MediaType.APPLICATION_JSON_VALUE)
Ja stimmt ist wirklich besser. Hatte es mit GET gelöst, da ich Schwierigkeiten hatte ein POST ohne CSRF Token abzuschicken. Habe dafür jetzt aber eine Lösung gefunden.

2021-08-05 10:36 UTC, maxones25 commented on src/main/java/de/hs_mannheim/informatik/ct/controller/RoomController.java
> +        model.addAttribute("roomResetEndpoint", roomResetEndpoint);
Da ja nur der Raumreset über JS gesteuert wird, braucht man bis auf den roomResetEndpoint und die redirectURI noch alle Attribute

2021-08-05 13:40 UTC, maxones25 commented on src/main/resources/templates/rooms/veranstaltungsleitenden-portal.html
> +						fetch("rest-room-reset")
habe ich jetzt umgesetzt

2021-08-05 13:41 UTC, maxones25 commented on src/main/resources/templates/rooms/veranstaltungsleitenden-portal.html
> +							const {success=false} = res || {}
ok habe ich übernommen

2021-08-05 13:41 UTC, maxones25 commented on src/main/java/de/hs_mannheim/informatik/ct/controller/RoomController.java
> +    public String executeRoomReset(
habe alle unnötigen Attribute entfernt

2021-08-09 19:38 UTC, MorMundHS-MA approved these changes

2021-08-09 20:07 UTC, merged